name: Publish-Docker-Image
on:
  push:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the image
        run: docker-compose up --build -d

      - name: Create a tag
        run: docker tag game-of-life_php-fpm aasanchez/game-of-life

      - name: Push the image to a registry
        run: docker push aasanchez/game-of-life:latest