name: Publish Docker image
on:
  push:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build
        run: docker-compose up --build -d
      - name: Build
        run: docker tag game-of-life_php-fpm aasanchez/game-of-life
      - name: Tag
        run: docker push aasanchez/game-of-life:latest